[package]
name = "turbonet"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.11", features = ["cuda-12010", "nvrtc", "driver"] }
tokio = { version = "1", features = ["full"] }
network-interface = "1.1"
rand = "0.8"
aes-gcm = "0.10"
aead = "0.5"
dotenvy = "0.15"
indicatif = "0.17"