[package]
name = "turbonet"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full", "rt-multi-thread"] }
cudarc = { version = "0.11", features = ["cuda-12000", "nvrtc", "driver"] }
network-interface = "1.1"
rand = "0.8"
aes-gcm = "0.10"
aead = "0.5"
dotenvy = "0.15"
indicatif = "0.17"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pqc_kyber = "0.7.1"
eframe = "0.29"
rfd = "0.12"
socket2 = "0.6.1"
local-ip-address = "0.6.8"
local_ipaddress = "0.1.3"
