[package]
name = "turbonet"
version = "0.1.0"
edition = "2021"

[dependencies]
cudarc = { version = "0.11", features = ["cuda-12010", "nvrtc", "driver"] }
tokio = { version = "1", features = ["full"] }
network-interface = "1.1"
rand = "0.8"

# This tells Cargo to automatically find all your scripts in src/bin/
[lib]
path = "src/lib.rs"